### ISSUE TITLE
The cloudmlmagic module is not an IPython extension

### ISSUE THREAD

**Issue by gprieto** [hayatoy/cloudml-magic#4]
Hello Hayato,

Thanks a lot for sharing this amazing work! Unfortunately I am not able to load the cloudmlmagic module after installing it with pip install, I get the following error:

`%load_ext cloudmlmagic`

> The cloudmlmagic module is not an IPython extension.

I was able to have it working though by manually copying the cloudmlmagic.py file into ~/.ipython/extensions but this gives a warning, in addition to the overhead of having to manually copy it:

`%load_ext cloudmlmagic`

> Loading extensions from ~/.ipython/extensions is deprecated. We recommend managing extensions like any other Python packages, in site-packages.

FYI I am running a python3 kernel within anaconda.

Any clues for what is causing this behaviour (which also appears when I try to load it in Colaboratory)?

BR
Guillermo

**Comment by hayatoy** [comment]
Hi @guilleralpoder ,

Thank you for your feedback! I haven't tested python 3 because Cloud ML Engine did not support.

Could you try following code instead?

```
%reload_ext cloudmlmagic
```

**Comment by gprieto** [comment]
Hey @hayatoy,

I got the problem fixed, it turns out that the import of the extension in ` __init__.py `changes with Python 3.
I will submit a PR to update it.

Thanks!

**Comment by hayatoy** [comment]
Hi @gprieto,
Great! Thank you!
