### ISSUE TITLE
Why not generate setup.py as expect?

### ISSUE THREAD

**Issue by jonascheng** [hayatoy/cloudml-magic#5]
Hi

  Thanks for providing such good extension, however I encounter problem as generating setup.py.

  This is how I configure the extension:
%ml_init -projectId datalab-trial-186403 -bucket cloudml_models/transfer_learning -scaleTier BASIC -region us-central1 -runtimeVersion 1.2 
{'install_requires': ['keras', 'h5py', 'Pillow']}

  Unfortunately, I'm getting empty install_requires below:
from setuptools import setup
if __name__ == '__main__':
    setup(name='trainer',
          packages=['trainer'],
          install_requires=[])

  I also traced your source and it looks fine to me. Hence I suspect that I might make some silly mistake. Would you give me a hand?

Thanks,
Jonas

**Comment by hayatoy** [comment]
Hi @jonascheng,
It looks like you are using old version that the function was not implemented,
Can you check if your notebook kernel loads latest version of cloudmlmagic?

Thanks!

**Comment by jonascheng** [comment]
Hi @hayatoy ,

  This is the version I installed, isn't it the latest version?

Name: cloudmlmagic
Version: 0.0.5
Summary: Jupyter Notebook Magics for Google Cloud ML Engine
Home-page: https://github.com/hayatoy/cloudml-magic
Author: Hayato Yoshikawa
Author-email: UNKNOWN
License: MIT
Location: /Users/jonas/.pyenv/versions/anaconda3-4.3.1/lib/python2.7/site-packages
Requires: google-api-python-client

Thanks,
Jonas

**Comment by hayatoy** [comment]
Hi @jonascheng ,

Yes it is the latest. Maybe `ex_settings` at Line53 is `None` in your case.
https://github.com/hayatoy/cloudml-magic/blob/master/cloudmlmagic/cloudmlmagic.py#L53

Could you watch the variable in your environment, or just simply print in each line?

Thanks

**Comment by jonascheng** [comment]
Hi @hayatoy 

  I found @line_cell_magic always give me None cell in my environment.

```
=> cloudmlmagic.py
    @line_cell_magic
    def ml_init(self, line, cell=None):
        """%ml_init
         -projectId PROJECTID
         -bucket BUCKET
         -region us-central1
         -scaleTier BASIC
         -runtimeVersion 1.0"""
        print('line: {} cell: {}'.format(line, cell))
```

```
=> output in notebook
line: -projectId datalab-trial-186403 -bucket cloudml_models/transfer_learning -scaleTier BASIC -region us-central1 -runtimeVersion 1.2 cell: None
```

  I tried several solutions but in vain, I still don't have idea to fix it.
  Do you think it's good idea to make install_requires a new cell magic, such as: %ml_install?

Thanks,
Jonas

**Comment by jonascheng** [comment]
Finally I figured out, you might need to update your [example](https://github.com/hayatoy/cloudml-magic/blob/master/examples/Keras_Fine_Tuning.ipynb) as well.

It works as I put extra % in front of ml_init
```
%%ml_init  -projectId datalab-trial-186403 -bucket cloudml_models/transfer_learning -scaleTier BASIC -region us-central1 -runtimeVersion 1.2 
{'install_requires': ['keras', 'h5py', 'Pillow']}
```

**Comment by hayatoy** [comment]
Hi @jonascheng ,
Thank you! I could reproduce the phenomenon and it seems my environment (Datalab) makes alias of the command automatically.

I will modify the example as cell command.
