### ISSUE TITLE
Does the package support python 3.x ?

### ISSUE THREAD

**Issue by bhanu-sharma** [hayatoy/cloudml-magic#7]
I have installed cloudmlmagic as per the instructions but when i run it in jupyter notebook ``` %load_ext cloudmlmagic```  
It shows the message: ``` The cloudmlmagic module is not an IPython extension. ```  
  
Send2Trash-1.4.2   bleach-2.1.2   decorator-4.2.1   html5lib-1.0.1   ipykernel-4.8.0   ipywidgets-7.1.0 jedi-0.11.1   jupyter-client-5.2.1   notebook-5.3.1   parso-0.1.1   pexpect-4.3.1   tornado-4.5.3 widgetsnbextension-3.1.0  python-3.5.2

**Comment by hayatoy** [comment]
Please refer to the issue https://github.com/hayatoy/cloudml-magic/issues/4
